Module3 task1
htmlacademy-adaptive/1585111-pognali-21 pull request #5
Opened 2020-12-01 21:14 UTC by Zhenia96

2020-12-02 10:52 UTC, Dima-Dim requested changes

2020-12-02 10:52 UTC, Dima-Dim commented on source/index.html
> +          <q class="main-page__text promo__quote">Лучшее приложение, что я видел в жизни!</q>
Элемент `main-page__text` вне блока `main-page`. И далее такая же проблема с элементами этого блока.

2020-12-02 10:52 UTC, Dima-Dim commented on source/sass/blocks/button.scss
> +  &__text {
В реально жизни вполне рабочее решение, но тут https://up.htmlacademy.ru/adaptive/21/criteries#d11

2020-12-02 10:52 UTC, Dima-Dim commented on source/sass/blocks/promo.scss
> +  .promo__slogan {
Думаю что здесь так тоже лучше не делать :)

2020-12-02 13:01 UTC, Zhenia96 commented on source/index.html
> +          <q class="main-page__text promo__quote">Лучшее приложение, что я видел в жизни!</q>
Класс "main-page" прописан в теге "html")

2020-12-02 13:05 UTC, Zhenia96 commented on source/sass/blocks/promo.scss
> +  .promo__slogan {
Я правильно понял ,что тут надо выносить элемент за тело блока, чтобы после компиляции вложенности небыло?
или в чем-то другом проблема?)

2020-12-02 13:05 UTC, Zhenia96 commented on source/sass/blocks/button.scss
> +  &__text {
Чет забыл про этот критерий)

2020-12-02 14:10 UTC, Dima-Dim commented on source/index.html
> +          <q class="main-page__text promo__quote">Лучшее приложение, что я видел в жизни!</q>
Всё ещё рекомендуют так делать? :)

2020-12-02 14:21 UTC, Zhenia96 commented on source/index.html
> +          <q class="main-page__text promo__quote">Лучшее приложение, что я видел в жизни!</q>
Не знаю), я сам так решил сделать, чтобы оформление текста привязать к странице. Т.к первый абзац во всех секциях страницы одинаково оформлен)

2020-12-04 04:38 UTC, Dima-Dim approved these changes

2020-12-04 04:38 UTC, merged